// This file is auto-generated by @hey-api/openapi-ts

export { client, type CreateClientConfig } from './client.gen';
export { GroupsToTabs, type Options } from './sdk.gen';
export type { ClientOptions, GetStartByTypeData, GetStartByTypeErrors, GetStartByTypeResponse, GetStartByTypeResponses, GroupsToTabsResponse } from './types.gen';
