// This file is auto-generated by @hey-api/openapi-ts

export const GroupsToTabsResponseSchema = {
    required: [
        'success',
        'message'
    ],
    type: 'object',
    properties: {
        success: {
            type: 'boolean'
        },
        message: {
            type: 'string'
        }
    }
} as const;
