// This file is auto-generated by @hey-api/openapi-ts

export const GroupsToTabsResponseSchema = {
    required: ['message', 'success'],
    type: 'object',
    properties: {
        success: {
            type: 'boolean'
        },
        message: {
            type: 'string'
        }
    },
    additionalProperties: false
} as const;