// This file is auto-generated by @hey-api/openapi-ts

import type { CancelablePromise } from './core/CancelablePromise';
import { OpenAPI } from './core/OpenAPI';
import { request as __request } from './core/request';
import type { GetUmbracoGroupsToTabsApiV1StartByTypeData, GetUmbracoGroupsToTabsApiV1StartByTypeResponse } from './types.gen';

/**
 * @param data The data for the request.
 * @param data.type
 * @returns unknown OK
 * @throws ApiError
 */
export const getUmbracoGroupsToTabsApiV1StartByType = (data: GetUmbracoGroupsToTabsApiV1StartByTypeData): CancelablePromise<GetUmbracoGroupsToTabsApiV1StartByTypeResponse> => { return __request(OpenAPI, {
    method: 'GET',
    url: '/umbraco/GroupsToTabs/api/v1/start/{type}',
    path: {
        type: data.type
    }
}); };