// This file is auto-generated by @hey-api/openapi-ts

export type GroupsToTabsResponse = {
    success: boolean;
    message: string;
};

export type GetUmbracoGroupsToTabsApiV1StartByTypeData = {
    body?: never;
    path: {
        type: string;
    };
    query?: never;
    url: '/umbraco/GroupsToTabs/api/v1/start/{type}';
};

export type GetUmbracoGroupsToTabsApiV1StartByTypeResponses = {
    /**
     * OK
     */
    200: GroupsToTabsResponse;
};

export type GetUmbracoGroupsToTabsApiV1StartByTypeResponse = GetUmbracoGroupsToTabsApiV1StartByTypeResponses[keyof GetUmbracoGroupsToTabsApiV1StartByTypeResponses];

export type ClientOptions = {
    baseUrl: 'http://localhost:54813' | (string & {});
};