// This file is auto-generated by @hey-api/openapi-ts

export type GroupsToTabsResponse = {
    success: boolean;
    message: string;
};

export type GetUmbracoGroupsToTabsApiV1StartByTypeData = {
    type: string;
};

export type GetUmbracoGroupsToTabsApiV1StartByTypeResponse = ((GroupsToTabsResponse));